[project]
name = "selinf_sampler"
dynamic = ["version"]
description  = "post-selection inference after lasso selection"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "scipy",
    "cvxpy",
    "autograd",
    "pandas",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "cython"
]
dev = [
    "pytest",
    "ninja",
    "meson",
    "meson-python",
    "pybind11",
    "setuptools_scm"
]

[build-system]
requires = [
    "meson-python",
    "pybind11",
    "numpy",
    "setuptools_scm",
    "ninja",
    "meson"
]
build-backend = "mesonpy"

[tool.setuptools_scm]
